// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: proto/signer.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

// GetPublicKeyResponse contains the public key information
type GetPublicKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 32-byte compressed Ristretto point
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// SS58 address derived from public_key
	Ss58Address string `protobuf:"bytes,2,opt,name=ss58_address,json=ss58Address,proto3" json:"ss58_address,omitempty"`
}

func (x *GetPublicKeyResponse) Reset() {
	*x = GetPublicKeyResponse{}
}

func (x *GetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse) ProtoMessage() {}

func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetPublicKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *GetPublicKeyResponse) GetSs58Address() string {
	if x != nil {
		return x.Ss58Address
	}
	return ""
}

// SignExtrinsicRequest contains the payload to sign
type SignExtrinsicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// SCALE-encoded payload to be signed
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional context for verification (nonce, era, etc.)
	Context []byte `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
}

func (x *SignExtrinsicRequest) Reset() {
	*x = SignExtrinsicRequest{}
}

func (x *SignExtrinsicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignExtrinsicRequest) ProtoMessage() {}

func (x *SignExtrinsicRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *SignExtrinsicRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignExtrinsicRequest) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

// SignExtrinsicResponse contains the signature
type SignExtrinsicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 64-byte sr25519 signature
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignExtrinsicResponse) Reset() {
	*x = SignExtrinsicResponse{}
}

func (x *SignExtrinsicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignExtrinsicResponse) ProtoMessage() {}

func (x *SignExtrinsicResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *SignExtrinsicResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}
