// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/signer.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetPublicKeyResponse contains the public key information
type GetPublicKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32-byte compressed Ristretto point
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// SS58 address derived from public_key
	Ss58Address string `protobuf:"bytes,2,opt,name=ss58_address,json=ss58Address,proto3" json:"ss58_address,omitempty"`
	// Key ID
	KeyId         string `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyResponse) Reset() {
	*x = GetPublicKeyResponse{}
	mi := &file_proto_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse) ProtoMessage() {}

func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{0}
}

func (x *GetPublicKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *GetPublicKeyResponse) GetSs58Address() string {
	if x != nil {
		return x.Ss58Address
	}
	return ""
}

func (x *GetPublicKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// GetPublicKeyByIDRequest specifies which key ID to get
type GetPublicKeyByIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key ID to get public key for
	KeyId         string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyByIDRequest) Reset() {
	*x = GetPublicKeyByIDRequest{}
	mi := &file_proto_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyByIDRequest) ProtoMessage() {}

func (x *GetPublicKeyByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyByIDRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeyByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublicKeyByIDRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// SignExtrinsicRequest contains the payload to sign with the default key
type SignExtrinsicRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SCALE-encoded payload to be signed
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional context for verification (nonce, era, etc.)
	Context       []byte `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignExtrinsicRequest) Reset() {
	*x = SignExtrinsicRequest{}
	mi := &file_proto_signer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignExtrinsicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignExtrinsicRequest) ProtoMessage() {}

func (x *SignExtrinsicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignExtrinsicRequest.ProtoReflect.Descriptor instead.
func (*SignExtrinsicRequest) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{2}
}

func (x *SignExtrinsicRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignExtrinsicRequest) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

// SignExtrinsicWithKeyRequest contains the payload to sign with a specific key
type SignExtrinsicWithKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key ID to use for signing
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// SCALE-encoded payload to be signed
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional context for verification (nonce, era, etc.)
	Context       []byte `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignExtrinsicWithKeyRequest) Reset() {
	*x = SignExtrinsicWithKeyRequest{}
	mi := &file_proto_signer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignExtrinsicWithKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignExtrinsicWithKeyRequest) ProtoMessage() {}

func (x *SignExtrinsicWithKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignExtrinsicWithKeyRequest.ProtoReflect.Descriptor instead.
func (*SignExtrinsicWithKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{3}
}

func (x *SignExtrinsicWithKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignExtrinsicWithKeyRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignExtrinsicWithKeyRequest) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

// SignExtrinsicResponse contains the signature
type SignExtrinsicResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 64-byte sr25519 signature
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Key ID used for signing
	KeyId         string `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignExtrinsicResponse) Reset() {
	*x = SignExtrinsicResponse{}
	mi := &file_proto_signer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignExtrinsicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignExtrinsicResponse) ProtoMessage() {}

func (x *SignExtrinsicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignExtrinsicResponse.ProtoReflect.Descriptor instead.
func (*SignExtrinsicResponse) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{4}
}

func (x *SignExtrinsicResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignExtrinsicResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// ListKeysResponse contains a list of all available key IDs
type ListKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of key IDs
	KeyIds []string `protobuf:"bytes,1,rep,name=key_ids,json=keyIds,proto3" json:"key_ids,omitempty"`
	// Default key ID (if set)
	DefaultKeyId  string `protobuf:"bytes,2,opt,name=default_key_id,json=defaultKeyId,proto3" json:"default_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysResponse) Reset() {
	*x = ListKeysResponse{}
	mi := &file_proto_signer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysResponse) ProtoMessage() {}

func (x *ListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysResponse.ProtoReflect.Descriptor instead.
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{5}
}

func (x *ListKeysResponse) GetKeyIds() []string {
	if x != nil {
		return x.KeyIds
	}
	return nil
}

func (x *ListKeysResponse) GetDefaultKeyId() string {
	if x != nil {
		return x.DefaultKeyId
	}
	return ""
}

var File_proto_signer_proto protoreflect.FileDescriptor

const file_proto_signer_proto_rawDesc = "" +
	"\n" +
	"\x12proto/signer.proto\x12\vbtsigner.v1\x1a\x1bgoogle/protobuf/empty.proto\"o\n" +
	"\x14GetPublicKeyResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12!\n" +
	"\fss58_address\x18\x02 \x01(\tR\vss58Address\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\"0\n" +
	"\x17GetPublicKeyByIDRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"J\n" +
	"\x14SignExtrinsicRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x18\n" +
	"\acontext\x18\x02 \x01(\fR\acontext\"h\n" +
	"\x1bSignExtrinsicWithKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x18\n" +
	"\acontext\x18\x03 \x01(\fR\acontext\"L\n" +
	"\x15SignExtrinsicResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"Q\n" +
	"\x10ListKeysResponse\x12\x17\n" +
	"\akey_ids\x18\x01 \x03(\tR\x06keyIds\x12$\n" +
	"\x0edefault_key_id\x18\x02 \x01(\tR\fdefaultKeyId2\xf1\x03\n" +
	"\fRemoteSigner\x12I\n" +
	"\fGetPublicKey\x12\x16.google.protobuf.Empty\x1a!.btsigner.v1.GetPublicKeyResponse\x12[\n" +
	"\x10GetPublicKeyByID\x12$.btsigner.v1.GetPublicKeyByIDRequest\x1a!.btsigner.v1.GetPublicKeyResponse\x12V\n" +
	"\rSignExtrinsic\x12!.btsigner.v1.SignExtrinsicRequest\x1a\".btsigner.v1.SignExtrinsicResponse\x12d\n" +
	"\x14SignExtrinsicWithKey\x12(.btsigner.v1.SignExtrinsicWithKeyRequest\x1a\".btsigner.v1.SignExtrinsicResponse\x12A\n" +
	"\bListKeys\x12\x16.google.protobuf.Empty\x1a\x1d.btsigner.v1.ListKeysResponse\x128\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB3Z1github.com/bittensor-lab/btsigner/proto/signer/v1b\x06proto3"

var (
	file_proto_signer_proto_rawDescOnce sync.Once
	file_proto_signer_proto_rawDescData []byte
)

func file_proto_signer_proto_rawDescGZIP() []byte {
	file_proto_signer_proto_rawDescOnce.Do(func() {
		file_proto_signer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_signer_proto_rawDesc), len(file_proto_signer_proto_rawDesc)))
	})
	return file_proto_signer_proto_rawDescData
}

var file_proto_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_signer_proto_goTypes = []any{
	(*GetPublicKeyResponse)(nil),        // 0: btsigner.v1.GetPublicKeyResponse
	(*GetPublicKeyByIDRequest)(nil),     // 1: btsigner.v1.GetPublicKeyByIDRequest
	(*SignExtrinsicRequest)(nil),        // 2: btsigner.v1.SignExtrinsicRequest
	(*SignExtrinsicWithKeyRequest)(nil), // 3: btsigner.v1.SignExtrinsicWithKeyRequest
	(*SignExtrinsicResponse)(nil),       // 4: btsigner.v1.SignExtrinsicResponse
	(*ListKeysResponse)(nil),            // 5: btsigner.v1.ListKeysResponse
	(*emptypb.Empty)(nil),               // 6: google.protobuf.Empty
}
var file_proto_signer_proto_depIdxs = []int32{
	6, // 0: btsigner.v1.RemoteSigner.GetPublicKey:input_type -> google.protobuf.Empty
	1, // 1: btsigner.v1.RemoteSigner.GetPublicKeyByID:input_type -> btsigner.v1.GetPublicKeyByIDRequest
	2, // 2: btsigner.v1.RemoteSigner.SignExtrinsic:input_type -> btsigner.v1.SignExtrinsicRequest
	3, // 3: btsigner.v1.RemoteSigner.SignExtrinsicWithKey:input_type -> btsigner.v1.SignExtrinsicWithKeyRequest
	6, // 4: btsigner.v1.RemoteSigner.ListKeys:input_type -> google.protobuf.Empty
	6, // 5: btsigner.v1.RemoteSigner.Health:input_type -> google.protobuf.Empty
	0, // 6: btsigner.v1.RemoteSigner.GetPublicKey:output_type -> btsigner.v1.GetPublicKeyResponse
	0, // 7: btsigner.v1.RemoteSigner.GetPublicKeyByID:output_type -> btsigner.v1.GetPublicKeyResponse
	4, // 8: btsigner.v1.RemoteSigner.SignExtrinsic:output_type -> btsigner.v1.SignExtrinsicResponse
	4, // 9: btsigner.v1.RemoteSigner.SignExtrinsicWithKey:output_type -> btsigner.v1.SignExtrinsicResponse
	5, // 10: btsigner.v1.RemoteSigner.ListKeys:output_type -> btsigner.v1.ListKeysResponse
	6, // 11: btsigner.v1.RemoteSigner.Health:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_signer_proto_init() }
func file_proto_signer_proto_init() {
	if File_proto_signer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_signer_proto_rawDesc), len(file_proto_signer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_signer_proto_goTypes,
		DependencyIndexes: file_proto_signer_proto_depIdxs,
		MessageInfos:      file_proto_signer_proto_msgTypes,
	}.Build()
	File_proto_signer_proto = out.File
	file_proto_signer_proto_goTypes = nil
	file_proto_signer_proto_depIdxs = nil
}
